services:
  - type: worker
    name: shopify-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python shopify.py
    envVars:
      - key: BOT_TOKEN
        sync: false
